name: Demo Workflow

on: [push]

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run JS Action
        uses: ./my-js-action   # local action
        with:
          name: Ayushi
